import { Button } from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import styles from "../shared/Home.module.css";
// import { Page1 } from "./page1";
import HomeIndexComp from "@components/home/index";
import NavBar from "@components/layout/navBar/navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* <NavBar /> */}
        <HomeIndexComp />
        {/* <Link href="/page1" passHref>
          <Button>Go to page 1</Button>
        </Link>
        <Link href="/page2" passHref>
          <Button>Add to Product Card</Button>
        </Link> */}
        {/* <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1> */}
      </main>
    </>
  );
}
